/**
 * core/state/strategyState.ts
 *
 * In-memory registry for strategy runtime states. Tracks the lifecycle,
 * signal counts, and PnL contribution of each registered strategy instance.
 *
 * Inputs:  Strategy start/stop/signal/order events from the Orchestrator.
 * Outputs: StrategyRuntimeState snapshots for frontend API and persistence.
 */

import { nowMs } from "../../utils/time";
import { newId } from "../../utils/ids";
import type { StrategyRuntimeState, StrategyRunStatus, StrategyType } from "../../types/strategy";
import type { StrategySignal } from "../../types/strategy";
import type { UUID } from "../../types/common";

export class StrategyStateManager {
  private states: Map<string, StrategyRuntimeState> = new Map();

  /**
   * Registers a new strategy and initializes its runtime state.
   * @param id - Strategy instance ID
   * @param type - Strategy algorithm type
   * @param name - Human-readable name
   */
  register(id: UUID, type: StrategyType, name: string): void {
    this.states.set(id, {
      id,
      type,
      name,
      status: "idle",
      signalCount: 0,
      orderCount: 0,
      realizedPnl: 0,
    });
  }

  /**
   * Returns the runtime state for a strategy, or null if not found.
   * @param id - Strategy instance ID
   * @returns StrategyRuntimeState or null
   */
  get(id: string): StrategyRuntimeState | null {
    return this.states.get(id) ?? null;
  }

  /**
   * Returns all registered strategy runtime states.
   * @returns Array of StrategyRuntimeState objects
   */
  getAll(): StrategyRuntimeState[] {
    return [...this.states.values()];
  }

  /**
   * Updates the status of a strategy.
   * @param id - Strategy instance ID
   * @param status - New StrategyRunStatus
   */
  setStatus(id: string, status: StrategyRunStatus): void {
    const state = this.states.get(id);
    if (!state) return;
    state.status = status;
    if (status === "running") state.startedAt = nowMs();
    if (status === "stopped") state.stoppedAt = nowMs();
  }

  /**
   * Records a new signal generated by a strategy.
   * @param id - Strategy instance ID
   * @param signal - The StrategySignal that was generated
   */
  recordSignal(id: string, signal: StrategySignal): void {
    const state = this.states.get(id);
    if (!state) return;
    state.signalCount++;
    state.lastSignal = signal;
  }

  /**
   * Increments the order count for a strategy.
   * @param id - Strategy instance ID
   */
  recordOrder(id: string): void {
    const state = this.states.get(id);
    if (!state) return;
    state.orderCount++;
  }

  /**
   * Adds realized PnL to a strategy's running total.
   * @param id - Strategy instance ID
   * @param pnl - Realized PnL to add (can be negative)
   */
  addRealizedPnl(id: string, pnl: number): void {
    const state = this.states.get(id);
    if (!state) return;
    state.realizedPnl += pnl;
  }

  /**
   * Records an error for a strategy and sets its status to "error".
   * @param id - Strategy instance ID
   * @param error - Error message
   */
  recordError(id: string, error: string): void {
    const state = this.states.get(id);
    if (!state) return;
    state.status = "error";
    state.lastError = error;
    state.stoppedAt = nowMs();
  }

  /**
   * Removes a strategy from the state registry.
   * @param id - Strategy instance ID
   */
  deregister(id: string): void {
    this.states.delete(id);
  }

  /** Clears all strategy states. Used in tests and resets. */
  clear(): void {
    this.states.clear();
  }
}
